export {
  AZ900_MOCK_EXAM,
  CERTIFICATIONS,
  DEFAULT_CERTIFICATION_ID,
  assertAvailableCertification,
  developmentIdPrefix,
  findDomain,
  findDomainLabel,
  findDomainShortLabel,
  getCertification,
  getCertificationByExamCode,
  getMockExamConfig,
  listAvailableCertifications,
  listCertifications,
  listComingSoonCertifications,
  normalizeCertificationKey,
  requireCertification,
  requireMockExamConfig,
  resolveCertificationId,
} from '@/certifications/catalog';
export {
  CERTIFICATION_STATUSES,
  DIFFICULTY_LEVELS,
  certificationTitle,
  isCertificationAvailable,
  type Certification,
  type CertificationDomain,
  type CertificationStatus,
  type CertificationTheme,
  type DifficultyLevel,
  type MockExamConfig,
} from '@/certifications/types';
